package FootballMarkerPro;


import java.util.Random;
import java.util.ArrayList;
import java.io.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gilby
 */
public class Campo extends javax.swing.JFrame {

    /**
     * Creates new form Campo
     */
    equipo[] teams;
    ArrayList<String> historial;
    Marcador history;
    public Campo() {
        initComponents();
        historial = new ArrayList<>();
        teams = new equipo[2];
        teams[0] = new equipo(texto1.getText());
        teams[1] = new equipo(texto.getText());
        history = new Marcador();
    }
    public void SetEquipos(String teamA, String teamB){
        
        texto1.setText(teamA);
        texto.setText(teamB);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        fondeishon = new javax.swing.JLabel();
        fondeishon2 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        Nombre1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        equipo1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        equipo2 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   0 : 0");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 190, 60));

        texto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 110, 15));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("HISTORIAL");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 130, 30));

        jButton6.setBackground(new java.awt.Color(0, 153, 51));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("JUGADOR EQUIPO 2");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 130, 30));

        jButton5.setBackground(new java.awt.Color(0, 153, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("DATOS DE EQUIPO 1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 130, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo negro 600 x360.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 190, 60));

        Nombre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo negro.png"))); // NOI18N
        Nombre2.setText("jLabel5");
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 160, 30));

        fondeishon.setBackground(new java.awt.Color(0, 102, 51));
        fondeishon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1024 back.jpg"))); // NOI18N
        fondeishon.setText("jLabel3");
        getContentPane().add(fondeishon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 180));

        fondeishon2.setBackground(new java.awt.Color(0, 102, 51));
        fondeishon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1024 back.jpg"))); // NOI18N
        fondeishon2.setText("jLabel3");
        getContentPane().add(fondeishon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 130, 180));

        texto1.setBackground(new java.awt.Color(255, 255, 255));
        texto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        texto1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 110, 15));

        jButton8.setBackground(new java.awt.Color(0, 153, 51));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("DATOS DE EQUIPO 2");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 130, 30));

        jButton9.setBackground(new java.awt.Color(0, 153, 51));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("JUGADOR EQUIPO 1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 130, 30));

        Nombre1.setBackground(new java.awt.Color(0, 0, 0));
        Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        Nombre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo negro.png"))); // NOI18N
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campo fut.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 300, 140));

        jScrollPane1.setBackground(new java.awt.Color(51, 255, 51));
        jScrollPane1.setForeground(new java.awt.Color(51, 255, 51));

        equipo1.setBackground(new java.awt.Color(51, 255, 51));
        jScrollPane1.setViewportView(equipo1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 180));

        jScrollPane2.setBackground(new java.awt.Color(51, 255, 51));

        equipo2.setBackground(new java.awt.Color(51, 255, 51));
        jScrollPane2.setViewportView(equipo2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 130, 180));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("cambiar equipos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 130, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Restart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 130, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Guardar Historial");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 120, 30));

        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/custom_1.jpg"))); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 340));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        texto2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        texto2.setForeground(new java.awt.Color(255, 255, 255));
        texto2.setText("jLabel6");
        getContentPane().add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        teams[0].setNombre(texto1.getText());
        teams[1].setNombre(texto.getText());
        Random ran = new Random();
        int atack = ran.nextInt(2);
        //Esta parte representa el flujo de ejecición del juego, donde cada evento representa una probabilidad definida
        for (int i=5;i<1000;i++){
            int r = ran.nextInt(100);
            if (r<90){
                boolean val = teams[atack].pases();
                if (!val){
                    atack = change(atack);
                    teams[atack].posbalon=ran.nextInt(teams[atack].cantJ);
                    historial.add("*Robo de Balon, equipo: "+teams[atack].getNombre()+"   minuto:"+String.valueOf(90*i/1000)+":"+String.valueOf(((90*i)%1000)*60/1000));
                }else{
                    //historial.add("Pase, equipo:"+String.valueOf(teams[atack].getEquipo())+"                minuto:"+String.valueOf(90*i/1000)+":"+String.valueOf(((90*i)%1000)*60/1000));
                }
                
            }else if(r<91){
                teams[atack].posbalon=ran.nextInt(teams[atack].cantJ);
                int f = ran.nextInt(2);
                teams[f].falta(historial,90*i/1000,((90*i)%1000)*60/1000);
                i++;
                //historial.add("Falta, equipo:"+String.valueOf(teams[f].getEquipo())+"                    minuto:"+String.valueOf(90*i/1000)+":"+String.valueOf(((90*i)%1000)*60/1000));
                if (f==1){
                    atack=0;
                }
                else{
                    atack=1;
                }
                teams[atack].posbalon=ran.nextInt(teams[atack].cantJ);
            }
            else if(r<96){
                if(!teams[atack].saque(historial,90*i/1000,((90*i)%1000)/1000)){
                    atack = change(atack);
                    teams[atack].posbalon=ran.nextInt(teams[atack].cantJ);
                    i++;
                }
                //historial.add("*Saque, equipo: "+String.valueOf(teams[atack].getNombre())+" minuto: "+String.valueOf(90*i/1000)+":"+String.valueOf(((90*i)%1000)/1000));
            }else{
                if (teams[atack].tiroalaPorteria(historial,90*i/1000,((90*i)%1000)/1000)){
                    atack = change(atack);
                    teams[atack].posbalon=ran.nextInt(teams[atack].cantJ);
                    i=i+4;
                }else{
                    i++;
                }
            }
        }
        jLabel4.setText("   "+teams[0].getPuntos()+" : " +teams[1].getPuntos());   
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

     //Esta funcion sirve para combiar el equipo que posee la pelota  
    public static int change(int n){
        if (n==1){
            return 0;
        }
        return 1;
    }
    //Esta funcion sirve para hacer visible los datos de un equipo
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Datos dat= new Datos();
        //teams[0].setNombre(jLabel2.getText());
        dat.llenarDatos(teams[0]);
        dat.setVisible(true); 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    //Esta funcion sirve para hacer hacer visible los datos de cada jugador de un equipo
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                //equipo1.setText("hola sdsadad sdasdsad sdsdsdsf dfdsfdsf dfdsfsd dfdsfsdfsd sdfsdfdsf sdfdsfsd fsdfsdf sdfsd fdsf sdf sdf sdfsdf sdfsd fsd fsdfdsf sd fsdf sdfsdfsdf sdf sdfsdf sdf sdfsdf dsf sdf sdf sdfsd fsdf sdf sdfs dfsdf sdf sdfsdfd fdf sdfsd fsdf dsf sdf sdf sd fsdfsdf sdf sdf df sdfsd fsd fsdf sdf sdfsd fsdf sdf sdf sdf sdf sdfsd fsdf sdf ");
                fondeishon2.setVisible(false);
                equipo2.setText(getDatosJugadores(teams[1]));
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        history.setVisible(true);
        history.llenarDatos(historial);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Datos Campo= new Datos();
        Campo.llenarDatos(teams[1]);

        Campo.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        fondeishon.setVisible(false);
        equipo1.setText(getDatosJugadores(teams[0]));
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        boolean verdad;
        
        if(JOptionPane.showConfirmDialog(null, "esta seguro de que desea reiniciar?") == 0){
       
        
        
        dispose();
        String TA =texto1.getText();
        String TB = texto.getText();
        
        Campo camp = new Campo();       
        camp.SetEquipos( TA, TB);
        camp.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "esta seguro de que desea cambiar de equipos?") == 0){
       
        dispose();
        Menu Men= new Menu();
        Men.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String nombre;
        
        nombre = JOptionPane.showInputDialog("introdusca el nombre del archivo");
        if(nombre.length() == 0){
            nombre = "default";
        }
        try{
        
        File f = new File(System.getProperty("user.home")+ "//Desktop//" + nombre + ".txt");    
        FileWriter fw = new FileWriter(f);
        BufferedWriter bw = new BufferedWriter(fw);
       
        int len = historial.size();
        for (int i=0;i<len;i++){
            bw.write(historial.get(i));
            bw.newLine();
        }
        
        bw.close();
        
        }
        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    public String getDatosJugadores(equipo team){
        String s="";
        for (int i=0;i<14;i++){
            s=s+team.getJugadores()[i];
        }
        
        return s;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Campo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    public static javax.swing.JTextPane equipo1;
    private javax.swing.JTextPane equipo2;
    public static javax.swing.JLabel fondeishon;
    private javax.swing.JLabel fondeishon2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel name;
    public static javax.swing.JLabel texto;
    public static javax.swing.JLabel texto1;
    public static javax.swing.JLabel texto2;
    // End of variables declaration//GEN-END:variables
}
