/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FootballMarkerPro;

import java.applet.AudioClip;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author gilby
 */
public class Menu extends javax.swing.JFrame {
      int xMouse;
      int yMouse;
      public AudioClip sonido; 
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param liga
     * @return 
     */
    @SuppressWarnings("unchecked")
    
     
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbEquipo1 = new javax.swing.JComboBox<>();
        cbEquipo = new javax.swing.JComboBox<>();
        cbLiga1 = new javax.swing.JComboBox<>();
        cbLiga = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EQUIPO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 40, 20));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("AR DELANEY", 1, 18)); // NOI18N
        jButton1.setText("COMENZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 150, 40));

        cbEquipo1.setBackground(new java.awt.Color(0, 0, 0));
        cbEquipo1.setFont(new java.awt.Font("Andalus", 1, 11)); // NOI18N
        cbEquipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEquipo1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 85, 25));

        cbEquipo.setBackground(new java.awt.Color(0, 0, 0));
        cbEquipo.setFont(new java.awt.Font("Andalus", 1, 11)); // NOI18N
        cbEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(cbEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 85, 25));

        cbLiga1.setBackground(new java.awt.Color(102, 102, 102));
        cbLiga1.setFont(new java.awt.Font("Andalus", 1, 10)); // NOI18N
        cbLiga1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija su Liga", "España", "Alemania", "Francia", "Italia", "Mexico", "Inglaterra", " " }));
        cbLiga1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLiga1ItemStateChanged(evt);
            }
        });
        cbLiga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLiga1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbLiga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 85, -1));

        cbLiga.setBackground(new java.awt.Color(102, 102, 102));
        cbLiga.setFont(new java.awt.Font("Andalus", 1, 10)); // NOI18N
        cbLiga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija Su Liga", "España", "Alemania", "Francia", "Italia", "Mexico", "Inglaterra", " " }));
        cbLiga.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cbLigaComponentAdded(evt);
            }
        });
        cbLiga.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLigaItemStateChanged(evt);
            }
        });
        cbLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLigaActionPerformed(evt);
            }
        });
        getContentPane().add(cbLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 85, -1));

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LIGA ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setBackground(new java.awt.Color(102, 102, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  EQUIPO 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 80, -1));

        jLabel3.setBackground(new java.awt.Color(102, 102, 0));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  EQUIPO 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo negro.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bola futbol.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 330));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public String[] getEquipo(String liga)
    {
     String[] equipo = new String[3];
     if(liga.equalsIgnoreCase("España"))
     {
         equipo[0] = "Real madrid";
         equipo[1] = "Barcelona";
         equipo[2] = "Atletico de Madrid";
                 
         
     }
     if(liga.equalsIgnoreCase("Alemania"))
     {
         equipo[0] = "Bayern Munich";
         equipo[1] = "Borussia Dortmund";
         equipo[2] = "Shalke 04";
         
     }
     if(liga.equalsIgnoreCase("Francia"))
     {
         equipo[0] = "Psg";
         equipo[1] = "Monaco";
         equipo[2] = "Lyon";
         
     }
     if(liga.equalsIgnoreCase("Mexico"))
     {
         equipo[0] = "Chivas";
         equipo[1] = "America";
         equipo[2] = "Cruz Azul";
         
     }
     if(liga.equalsIgnoreCase("Inglaterra"))
     {
         equipo[0] = "Chelsea";
         equipo[1] = "Manchester United";
         equipo[2] = "Liverpool";
         
     }
     if(liga.equalsIgnoreCase("Italia"))
     {
         equipo[0] = "Milan";
         equipo[1] = "Juventus";
         equipo[2] = "Inter";
         
     }
     return equipo;
    }
    private void cbLiga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLiga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLiga1ActionPerformed

    private void cbLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLigaActionPerformed
        
    }//GEN-LAST:event_cbLigaActionPerformed

    private void cbLigaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbLigaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLigaComponentAdded

    private void cbLigaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLigaItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            if(this.cbLiga.getSelectedIndex()> 0)
            {
                this.cbEquipo.setModel(new DefaultComboBoxModel(this.getEquipo(this.cbLiga.getSelectedItem().toString())));
            }
        }
        
         
    }//GEN-LAST:event_cbLigaItemStateChanged

    private void cbLiga1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLiga1ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            if(this.cbLiga1.getSelectedIndex()> 0)
            {
                this.cbEquipo1.setModel(new DefaultComboBoxModel(this.getEquipo(this.cbLiga1.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_cbLiga1ItemStateChanged

    private void cbEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEquipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        
        if(cbEquipo.getSelectedIndex() >= 0 && cbEquipo1.getSelectedIndex() >= 0){
        dispose();
        Campo camp = new Campo();       
        
        camp.setVisible(true);
        camp.SetEquipos(cbEquipo.getSelectedItem().toString(),cbEquipo1.getSelectedItem().toString());     
            
        }
        else{
                 JOptionPane.showMessageDialog(rootPane,"Elija un equipo" );
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbEquipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEquipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEquipo1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEquipo;
    private javax.swing.JComboBox<String> cbEquipo1;
    private javax.swing.JComboBox<String> cbLiga;
    private javax.swing.JComboBox<String> cbLiga1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
